<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ApiToken', 'doctrine');

/**
 * BaseApiToken
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $token
 * 
 * @method integer  getId()    Returns the current record's "id" value
 * @method string   getToken() Returns the current record's "token" value
 * @method ApiToken setId()    Sets the current record's "id" value
 * @method ApiToken setToken() Sets the current record's "token" value
 * 
 * @package    orangehrm_api
 * @subpackage model
 * @author     S W L Silva
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseApiToken extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('api_token');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}