<?php

/**
 * ApiTokenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApiTokenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ApiTokenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ApiToken');
    }
}