<?php

/**
 * Employee
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm_api
 * @subpackage model
 * @author     S W L Silva
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Employee extends BaseEmployee
{
    public function asArray($user_name)
    {
        return array(
            'user_name'     => $user_name,
            'id'            => $this->getId(),
            'first_name'    => $this->getFirst_Name(),
            'last_name'     => $this->getLast_Name(),
            'address'       => $this->getAddress(),
        );        
    }
}