<?php

/**
 * User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    orangehrm_api
 * @subpackage model
 * @author     S W L Silva
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class User extends BaseUser
{
    public function save(Doctrine_Connection $conn = null)
    {
      if (!$this->getPassword())
      {
        $this->setPassword(md5($this->getPassword()));
      }
   
      return parent::save($conn);
    }   
}