<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2023/01/24 17:24:25

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql://root:anroiD741@localhost:3307/orangehrm',
  'username' => 'root',
  'password' => 'anroiD741',
  'name' => 'doctrine',
)),);
